name: 'Test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: 'Test the K8S Deployer Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout this repository'
        uses: actions/checkout@v3

      - name: 'Run the K8S Deployer Action'
        uses: ./
        with:
          namespace: 'testname'
          releaseName: 'test-release'
          values: |
            containerPort:4321
          valueFiles: |
            ./.github/workflows/test/_common.yaml
            ./.github/workflows/test/develop.yaml
#          chart: 'test-chart'
#          helmVersion: 'v3.10.2'
#          repoUrl: "https://charts.helm.sh/stable"
#          repoName: "stable"
