name: 'Test'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: 'Test the K8S Deployer Action'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout this repository'
        uses: actions/checkout@v3

      - name: 'Run the K8S Deployer Action'
        uses: ./
        with:
          namespace: 'test'
          releaseName: 'test-release'
          chart: 'test-chart'
          helmVersion: 'v3.10.2'
          values: |
            replicaCount: 1
          valueFiles: |
            ./helm/staging.yaml
          repoUrl: "https://charts.helm.sh/stable"
          repoName: "stable"
