name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - name: Run my action
        uses: ./
